contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - ingress-nginx-controller-1.12
    - ingress-nginx-controller-compat-1.12
    - heimdal-libs
    - icu-libs
    - libfontconfig1
    - msgpack-cxx

work-dir: /etc/nginx

accounts:
  groups:
    - groupname: www-data
      gid: 65532
  users:
    - username: www-data
      uid: 65532
  run-as: www-data

entrypoint:
  command: /nginx-ingress-controller

cmd: /usr/bin/dumb-init ---

paths:
  - path: /etc/ingress-controller
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o750
  - path: /tmp/nginx
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o750
  - path: /etc/nginx/lua
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o750
  

environment:
  LUA_CPATH: /usr/lib/lua/5.1/?.so;/usr/lib/lua/?/?.so;/usr/lib/lua/?.so;/usr/lib/lua/?.lua;
  LUA_PATH: /usr/share/lua/5.1/?.lua;/usr/lib/lua/?.lua;/usr/lib/lua/?.lua;/usr/share/lua/?.lua
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/luajit/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

archs:
  - x86_64
